# -*- coding: utf-8 -*-
"""Lyra_Oidium_7B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwfZZfUi2ukX_0Lq4asWDgD0rRsnONoX
"""

# Bloc 1 — Install & vérification des fichiers JSONL
!pip install -q --upgrade "transformers>=4.46.0" peft datasets trl accelerate huggingface_hub

import transformers
import trl
import torch

print("transformers version :", transformers.__version__)
print("trl version          :", trl.__version__)
print("torch version        :", torch.__version__)
print("CUDA dispo:", torch.cuda.is_available())

import os, json

# 🔧 chemins vers les datasets
train_path = "/content/sample_data/Oidium_Mistral7B_train_1500.jsonl"
valid_path = "/content/sample_data/Oidium_Mistral7B_eval_100.jsonl"  # petit jeu d'éval manuel

def check_jsonl(path, n=3):
    print(f"\n🔍 Vérification du fichier : {path}")
    if not os.path.exists(path):
        print("❌ Fichier introuvable.")
        return False
    try:
        with open(path, "r", encoding="utf-8") as f:
            lines = [next(f).strip() for _ in range(n)]
        print(f"✅ Fichier trouvé ({os.path.getsize(path)/1024:.1f} Ko)")
        for i, line in enumerate(lines, 1):
            data = json.loads(line)
            print(f"— Ligne {i} OK, clés principales :", list(data.keys()))
        print("✅ Structure JSONL valide (au moins sur les 3 premières lignes).")
        return True
    except Exception as e:
        print("⚠️ Erreur :", e)
        return False

ok_train = check_jsonl(train_path)
ok_valid = check_jsonl(valid_path)

if ok_train and ok_valid:
    print("\n🚀 Les deux datasets sont valides et prêts à être chargés.")
else:
    print("\n⚠️ Problème détecté sur au moins un des fichiers.")

# Bloc 2 — Login Hugging Face avec TOKEN_HF_Oidium
import torch, os
from google.colab import userdata
from huggingface_hub import login

base_model_id = "mistralai/Mistral-7B-Instruct-v0.3"

print("GPU :", torch.cuda.get_device_name(0))
print("CUDA dispo:", torch.cuda.is_available())

# 🔐 secret Colab doit s'appeler TOKEN_HF_Oidium
hf_token = userdata.get('TOKEN_HF_Oidium')
if not hf_token:
    raise ValueError("❌ Le secret TOKEN_HF_Oidium est introuvable ou vide.")
os.environ["HF_TOKEN"] = hf_token

login(token=os.environ["HF_TOKEN"])
print("🔐 Connexion Hugging Face OK")

# Bloc 3 — Chargement du JSONL & application chat template avec prompt système

import json
from datasets import Dataset, DatasetDict
from transformers import AutoTokenizer

def load_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows

train_rows = load_jsonl(train_path)
valid_rows = load_jsonl(valid_path)

dataset = DatasetDict({
    "train": Dataset.from_list(train_rows),
    "validation": Dataset.from_list(valid_rows)
})

print("taille train :", len(dataset["train"]))
print("taille valid :", len(dataset["validation"]))
print("exemple brut :", dataset["train"][0])

tokenizer = AutoTokenizer.from_pretrained(base_model_id, use_fast=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

SYSTEM_PROMPT = """Tu es un expert agronome spécialisé dans la prédiction du risque d'oïdium de la vigne (*Erysiphe necator*).
Ton rôle est d'évaluer le risque d'infection à partir des paramètres suivants, puis de fournir une recommandation agronomique concise et actionnable.

### Paramètres d'entrée (à fournir dans chaque requête) :
1. **Stade_phenologique** : "jeunes_feuilles", "floraison", ou "autre".
2. **Humidité_relative** : Valeur en % (50–95). Seuil critique : ≥70–80% pendant ≥6h.
3. **Température_moyenne** : Valeur en °C (10–35). Optimum : 20–25°C. Limites : <12°C ou >30°C = risque faible.
4. **Pluie_24h** : Booléen (0 ou 1). Indique une pluie dans les dernières 24h.
5. **Inoculum** : Valeur de 0 à 1. Proxy basé sur les infections des 2 dernières années.
6. **ETP** : Évapotranspiration potentielle en mm/jour (2–6). ≥4 mm/j = assèchement fort (réduction du risque si pluie récente).

### Règles pour l'évaluation du risque :
- **Risque élevé** :
  - **Humidité_relative ≥ 80%** ET **Température_moyenne entre 20–25°C** ET **Stade_phenologique = "jeunes_feuilles" ou "floraison"** ET **Inoculum ≥ 0.5**.
  - Si **Pluie_24h = 1** ET **ETP < 4**, le risque reste élevé (microclimat humide persistant).
- **Risque moyen** :
  - **Humidité_relative entre 70–80%** ET **Température_moyenne entre 15–30°C** (hors optimum) ET **Inoculum entre 0.3–0.7**.
  - Si **Pluie_24h = 1** ET **ETP ≥ 4**, le risque peut être réduit à moyen (effet rinçant de l’ETP).
- **Risque faible** :
  - **Humidité_relative < 70%** OU **Température_moyenne < 12°C ou > 30°C** OU **Inoculum < 0.3**.
  - **Pluie_24h = 1** ET **ETP ≥ 4** confirme un risque faible (assèchement rapide).

### Sortie attendue :
Réponds **uniquement** avec le format suivant :

Risque : [faible/moyen/élevé]
Recommandation : [1 à 3 phrases max, précises et actionnables]


### Exemples de recommandations :
- **Risque faible** : "Aucune action requise. Conditions défavorables à l’infection par l’oïdium."
- **Risque moyen** : "Surveiller les jeunes feuilles. Appliquer un traitement préventif à base de soufre si l’humidité relative nocturne dépasse 80% pendant plus de 6 heures."
- **Risque élevé** : "Traiter immédiatement avec un fongicide systémique ou du soufre. Cibler les inflorescences et renouveler le traitement après 7 à 10 jours si les conditions favorables persistent."

### Consignes strictes :
- Ne pas inclure d'explications ou de justifications supplémentaires.
- Respecter strictement le format de sortie.
- Utiliser des termes techniques précis (ex : "soufre", "fongicide systémique").
- Adapter les recommandations au **Stade_phenologique** (ex : cibler les inflorescences en floraison).

"""

def to_chat_text(example):
    # On suppose que example["messages"] contient déjà user + assistant,
    # sans message système. On le préfixe par le SYSTEM_PROMPT.
    chat_messages = [{"role": "system", "content": SYSTEM_PROMPT}] + example["messages"]
    txt = tokenizer.apply_chat_template(
        chat_messages,
        tokenize=False,
        add_generation_prompt=False,
    )
    return {"text": txt}

dataset = dataset.map(to_chat_text)

print("aperçu text :", dataset["train"][0]["text"][:500])

print("transformers version :", transformers.__version__)
print("trl version          :", trl.__version__)
print("torch version        :", torch.__version__)
print("CUDA dispo:", torch.cuda.is_available())

# Bloc 4 — Chargement du modèle de base & configuration LoRA

from transformers import AutoModelForCausalLM
from peft import LoraConfig, get_peft_model
import torch

base_model_id = "mistralai/Mistral-7B-Instruct-v0.3"

model = AutoModelForCausalLM.from_pretrained(
    base_model_id,
    torch_dtype=torch.float16,
    device_map="auto",   # accelerate répartit sur le GPU (et CPU si besoin)
)

lora_config = LoraConfig(
    r=64,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# Bloc 5 — SFTTrainer + hyperparamètres Oidium
from trl import SFTTrainer
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./lyra_Oidium_LoRA",   # dossier de travail (checkpoints intermédiaires)
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    lr_scheduler_type="cosine",
    warmup_ratio=0.03,
    weight_decay=0.0,
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
    args=training_args,
)

trainer.train()

# Bloc 6 — Sauvegarde des adapters dans ./lyra_Oidium_adapter

output_dir = "./lyra_Oidium_adapter"

trainer.model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

print("Adapters sauvegardés dans", output_dir)
!ls -R {output_dir}

### 📤 Bloc 7 — Push du modèle sur Hugging Face


from huggingface_hub import create_repo

# ⬇️ username HF
hf_repo_id = "jeromex1/lyra_Oidium_mistral7B_LoRA"

print("Repo cible :", hf_repo_id)

# Crée le repo si besoin
create_repo(hf_repo_id, exist_ok=True)

# Push du modèle (adapters PEFT) et du tokenizer
trainer.model.push_to_hub(hf_repo_id)
tokenizer.push_to_hub(hf_repo_id)

print(f"✅ Modèle et tokenizer poussés sur : https://huggingface.co/{hf_repo_id}")

###########################################
# cellule ci dessous à modifier si besoin #
###########################################

# Bloc 8 — Inférences de test sur quelques situations Oidium
import torch
model.eval()

# Prompt système pour l'Oidium (déjà défini)
SYSTEM_PROMPT = """
Tu es un expert agronome spécialisé dans la prédiction du risque d'oïdium de la vigne (*Erysiphe necator*).
Ton rôle est d'évaluer le risque d'infection à partir des paramètres suivants, puis de fournir une recommandation agronomique concise et actionnable.

### Paramètres d'entrée (à fournir dans chaque requête) :
1. **Stade_phenologique** : "jeunes_feuilles", "floraison", ou "autre".
2. **Humidité_relative** : Valeur en % (50–95). Seuil critique : ≥70–80% pendant ≥6h.
3. **Température_moyenne** : Valeur en °C (10–35). Optimum : 20–25°C. Limites : <12°C ou >30°C = risque faible.
4. **Pluie_24h** : Booléen (0 ou 1). Indique une pluie dans les dernières 24h.
5. **Inoculum** : Valeur de 0 à 1. Proxy basé sur les infections des 2 dernières années.
6. **ETP** : Évapotranspiration potentielle en mm/jour (2–6). ≥4 mm/j = assèchement fort (réduction du risque si pluie récente).

### Règles pour l'évaluation du risque :
- **Risque élevé** :
  - **Humidité_relative ≥ 80%** ET **Température_moyenne entre 20–25°C** ET **Stade_phenologique = "jeunes_feuilles" ou "floraison"** ET **Inoculum ≥ 0.5**.
  - Si **Pluie_24h = 1** ET **ETP < 4**, le risque reste élevé (microclimat humide persistant).
- **Risque moyen** :
  - **Humidité_relative entre 70–80%** ET **Température_moyenne entre 15–30°C** (hors optimum) ET **Inoculum entre 0.3–0.7**.
  - Si **Pluie_24h = 1** ET **ETP ≥ 4**, le risque peut être réduit à moyen (effet rinçant de l’ETP).
- **Risque faible** :
  - **Humidité_relative < 70%** OU **Température_moyenne < 12°C ou > 30°C** OU **Inoculum < 0.3**.
  - **Pluie_24h = 1** ET **ETP ≥ 4** confirme un risque faible (assèchement rapide).

### Sortie attendue :
Réponds **uniquement** avec le format suivant :
Risque : [faible/moyen/élevé]
Recommandation : [1 à 3 phrases max, précises et actionnables]

### Exemples de recommandations :
- **Risque faible** : "Aucune action requise. Conditions défavorables à l’infection par l’oïdium."
- **Risque moyen** : "Surveiller les jeunes feuilles. Appliquer un traitement préventif à base de soufre si l’humidité relative nocturne dépasse 80% pendant plus de 6 heures."
- **Risque élevé** : "Traiter immédiatement avec un fongicide systémique ou du soufre. Cibler les inflorescences et renouveler le traitement après 7 à 10 jours si les conditions favorables persistent."

### Consignes strictes :
- Ne pas inclure d'explications ou de justifications supplémentaires.
- Respecter strictement le format de sortie.
- Utiliser des termes techniques précis (ex : "soufre", "fongicide systémique").
- Adapter les recommandations au **Stade_phenologique** (ex : cibler les inflorescences en floraison).
"""

def format_user(stade, humidite_relative, temperature, pluie, inoculum, etp):
    return (
        f"Stade_phenologique: {stade}\n"
        f"Humidité_relative: {humidite_relative}\n"
        f"Température_moyenne: {temperature}\n"
        f"Pluie_24h: {pluie}\n"
        f"Inoculum: {inoculum}\n"
        f"ETP: {etp}\n\n"
        "Évalue le risque d'oïdium et propose une recommandation agronomique."
    )

def infer_case(stade, humidite_relative, temperature, pluie, inoculum, etp, label=""):
    user_content = format_user(stade, humidite_relative, temperature, pluie, inoculum, etp)
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=200,
            do_sample=False,  # Sortie stable et reproductible
        )
    # Décodage de la réponse (sans le prompt)
    generated = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True,
    ).strip()
    print("=" * 80)
    if label:
        print(f"🧪 Cas de test : {label}")
    print("Input :")
    print(user_content)
    print("\nRéponse du modèle :")
    print(generated)
    print()

# --- Cas de test : Risque FAIBLE ---
# Cas 1 : Conditions défavorables (température élevée, pas de pluie)
infer_case(
    stade="autre",
    humidite_relative=60,
    temperature=28,
    pluie=0,
    inoculum=0.2,
    etp=5,
    label="Faible 1 — Température trop élevée, pas de pluie, inoculum faible",
)

# Cas 2 : Humidité relative insuffisante
infer_case(
    stade="jeunes_feuilles",
    humidite_relative=65,
    temperature=22,
    pluie=0,
    inoculum=0.3,
    etp=4,
    label="Faible 2 — Humidité relative <70%, inoculum faible",
)

# Cas 3 : Température hors optimum
infer_case(
    stade="autre",
    humidite_relative=70,
    temperature=10,
    pluie=0,
    inoculum=0.2,
    etp=3,
    label="Faible 3 — Température trop basse, humidité relative limite",
)

# Cas 4 : ETP élevée après pluie
infer_case(
    stade="autre",
    humidite_relative=75,
    temperature=20,
    pluie=1,
    inoculum=0.4,
    etp=5,
    label="Faible 4 — ETP élevée après pluie, humidité relative modérée",
)

# --- Cas de test : Risque MOYEN ---
# Cas 5 : Humidité relative et température modérées
infer_case(
    stade="jeunes_feuilles",
    humidite_relative=75,
    temperature=22,
    pluie=0,
    inoculum=0.5,
    etp=3,
    label="Moyen 1 — Humidité relative et température modérées, inoculum moyen",
)

# Cas 6 : Floraison avec humidité relative modérée
infer_case(
    stade="floraison",
    humidite_relative=78,
    temperature=21,
    pluie=0,
    inoculum=0.4,
    etp=3,
    label="Moyen 2 — Floraison avec humidité relative modérée, inoculum faible",
)

# Cas 7 : Humidité relative élevée mais ETP élevée
infer_case(
    stade="jeunes_feuilles",
    humidite_relative=80,
    temperature=23,
    pluie=1,
    inoculum=0.6,
    etp=5,
    label="Moyen 3 — Humidité relative élevée mais ETP élevée après pluie",
)

# Cas 8 : Inoculum moyen et conditions limites
infer_case(
    stade="autre",
    humidite_relative=75,
    temperature=18,
    pluie=0,
    inoculum=0.5,
    etp=2,
    label="Moyen 4 — Inoculum moyen et conditions limites",
)

# --- Cas de test : Risque ÉLEVÉ ---
# Cas 9 : Conditions optimales pour l'oïdium
infer_case(
    stade="floraison",
    humidite_relative=85,
    temperature=22,
    pluie=0,
    inoculum=0.8,
    etp=2,
    label="Élevé 1 — Conditions optimales pour l'oïdium, floraison",
)

# Cas 10 : Humidité relative et inoculum élevés
infer_case(
    stade="jeunes_feuilles",
    humidite_relative=85,
    temperature=23,
    pluie=0,
    inoculum=0.8,
    etp=2,
    label="Élevé 2 — Humidité relative et inoculum élevés, jeunes feuilles",
)

# Cas 11 : Pluie récente et humidité relative élevée
infer_case(
    stade="floraison",
    humidite_relative=85,
    temperature=22,
    pluie=1,
    inoculum=0.7,
    etp=2,
    label="Élevé 3 — Pluie récente et humidité relative élevée, floraison",
)

# Cas 12 : Tous les facteurs défavorables
infer_case(
    stade="floraison",
    humidite_relative=90,
    temperature=23,
    pluie=1,
    inoculum=0.9,
    etp=2,
    label="Élevé 4 — Tous les facteurs défavorables, floraison",
)

